name: sync

on:
  push:
  schedule: 
  - cron: "*/5 * * * *"

jobs:
  sync:
    name: sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        source_repo: git@github.com:joe-choi-dev/test1.git
        source_branch: main
        destination_branch: main
        github_token: ${{ secrets.SSH_PRIVATE_KEY }}
