# .github/workflows/git-sync.yml

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: wei/git-sync
          path: git-sync
      - name: echo
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "github.workspace = ${{ github.workspace }}"
          ls "${{ github.workspace }}/git-sync"
      - name: git-sync
        # uses: wei/git-sync@v3
        uses: "/home/runner/work/test1/test1/git-sync"
        with:
          source_repo: "git@github.com:joe-choi-dev/test1.git"
          source_branch: "main"
          destination_repo: "git@github.com:joe-choi-dev/test2.git"
          destination_branch: "main"
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`