name: Joe - Sync Repos

on:
  schedule: 
  - cron: "*/15 * * * *" # every 15 minutes. set to whatever interval you like

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      with:
        source_repo: https://github.com/joe-choi-dev/test1
        source_branch: main
        destination_branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
